# Problems 2.4

$$ \newcommand{\uvec}[1]{\hat{\mathbf{#1}}} $$

1. Let $\uvec i$ point torward the vernal equinox, $\uvec k$ toward the celestial north pole, $\uvec m$ toward the summer solstice, and $\uvec n$ toward the north pole of the ecliptic. Express $\uvec i$ in terms of $\uvec n$ and $\uvec k$; $\uvec m$ in terms of $\uvec n$ and $\uvec k$; $\uvec n$ in terms of $\uvec i$ and $\uvec k$; $\uvec k$ in terms of $\uvec i$ and $\uvec n$.

<img src="Problems_2.4.1.png" style="max-width: 80%"></img>

<!-- replace the graphic here -->

$$
\begin{align}
\uvec i &= \frac{\uvec k \times \uvec n}{\sin \theta} \\
\uvec m &= \uvec n \times \uvec i = \uvec n \times \left(\frac{\uvec k \times \uvec n}{\sin \theta}\right) \\
\uvec n &= \sin(\theta)(\uvec k \times \uvec i) + \cos(\theta)\uvec k \\
\uvec k &= \cos(\theta)\uvec n + \sin(\theta)\uvec m;\ \theta < 0 \\
\uvec k &= \cos(\theta)\uvec n + \sin(\theta)(\uvec n \times \uvec i);\ \theta < 0 \\
\end{align} $$

2. Prove the formula for the triple vector product.

The formula of the triple vector product is:

$$ \vec a \times (\vec b \times \vec c) = (\vec a \cdot \vec c)\vec b - (\vec a \cdot \vec b)\vec c $$

Let's simply try verifying it by expanding both expressions algebraically.

In [13]:
import warnings
from sympy import *
init_printing()
from sympy.vector import CoordSys3D, Vector

warnings.filterwarnings("ignore", category=UserWarning)
N = CoordSys3D('N')

In [2]:
a = symbols('a:3')
b = symbols('b:3')
c = symbols('c:3')

In [3]:
av = a[0]*N.i + a[1]*N.j + a[2]*N.k
bv = b[0]*N.i + b[1]*N.j + b[2]*N.k
cv = c[0]*N.i + c[1]*N.j + c[2]*N.k

In [4]:
tripleCross = av.cross(bv.cross(cv))
tripleCross

In [5]:
tripleCrossEquiv = (av.dot(cv))*bv - (av.dot(bv))*cv
tripleCrossEquiv

In [6]:
diff = tripleCross - tripleCrossEquiv
diff

In [7]:
simplify(diff)

3. If $\vec a + \vec b + \vec c = 0$, show that 

    $$ \vec b \times \vec c = \vec c \times \vec a = \vec a \times \vec b $$

    and interpret geometrically.

The magnitudes of the cross products are the areas of the parellelograms formed by the constituent vectors. If all the vectors sum to zero, then those areas are the same. They're also co-planar, so those cross products are identical normal vectors.

4. What is the locus of $\vec r$ such that $[\vec r, \vec a, \vec b] = 0$?

The vector $\vec r$ is all vectors in the plane defined by vectors $\vec a$ and $\vec b$. This is because

$$[\vec r, \vec a, \vec b] = \vec r \cdot (\vec a \times \vec b) = 0 $$

Which we should recognize, by now, as the dot product of a variable vector $\vec r$ with a vector normal to the plane of $\vec a$ and $\vec b$.

5. If $l$, $m$, and $n$ are three nonzero scalars, and 

    $$ l\vec a + m\vec b + n\vec c = 0 $$
    
    show that $\vec a$, $\vec b$, and $\vec c$ are coplanar. If also
    
    $$ l'\vec a + m'\vec b + n'\vec c = 0 $$
    
    show that
    
    $$ \frac{l}{l'} = \frac{m}{m'} = \frac{n}{n'} $$

It becomes obvious after playing with the interactive diagram that since

$$ l\vec a + m\vec b + n\vec c = 0 $$

and 

$$ l\vec a + m\vec b = n\vec c $$

we can think of $\vec c$ as the sum of $\vec a$ and $\vec b$ mirrored across the  origin. Since the sum of $\vec a$ and $\vec b$ also lays in the plane that $\vec a$ and $\vec b$ form with the origin, it follows that $-(\vec a + \vec b)$ will lay in the same plane.

6. If $\vec x$, $\vec a$, and $\vec b$ are coplanar, show that usually $\vec x$ can be expressed as

    $$ \vec x = \lambda\vec a + \mu\vec b $$
    
    What is the exception to this?

The exception is when $\vec a$ and $\vec b$ are colinear and $\vec x$ is not.

7. Evaluate $(\vec a + \vec b) \times (\vec a - \vec b)$.

We can expand it like a polynomial, eliminate doubles, and subsitute the negatives for the reversed.

$$\begin{align}
(\vec a + \vec b) \times (\vec a - \vec b) &= \vec a \times \vec a - (\vec a \times \vec b) + (\vec b \times \vec a) - (\vec b \times \vec b) \\
&= 0 - (\vec a \times \vec b) + (\vec b \times \vec a) - 0 \\
&= (\vec b \times \vec a) + (\vec b \times \vec a) \\
&= 2(\vec b \times \vec a)
\end{align}$$



8. Choosing simple (but not trivial) numerical values for the components of $\vec a$, $\vec b$, and $\vec c$, verify numerically that

    $$ \vec a \cdot (\vec b + \vec c) = \vec a \cdot \vec b + \vec a \cdot \vec c, \quad \vec a \times (\vec b + \vec c) = \vec a \times \vec b + \vec a \times \vec c, \\
    \vec a \times (\vec b \times \vec c) = (\vec a \cdot \vec c)\vec b - (\vec a \cdot \vec b)c $$
    
    Find the values of
    
    $$ |\vec a \times \vec c|, \quad [\vec a, \vec b, \vec c], \quad (\vec a \times \vec b) \times \vec c, \quad (\vec a \times \vec b) \cdot (\vec a \times \vec c), \quad (\vec a \times \vec b) \times (\vec a \times \vec c) $$

In [2]:
import numpy as np
from numpy import cross, dot

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [3]:
dot(a, b+c) - (dot(a, b) + dot(a, c))

0

In [4]:
cross(a, b+c) - (cross(a, b) + cross(a, c))

array([0, 0, 0])

In [5]:
cross(a, cross(b, c)) - (dot(a, c)*b - dot(a, b)*c)

array([0, 0, 0])

In [6]:
np.linalg.norm(cross(a, c))

14.696938456699069

In [7]:
dot(a, cross(b, c))

0

In [8]:
cross(cross(a, b), c)

array([ 78,   6, -66])

In [9]:
dot(cross(a, b), cross(a, c))

108

In [10]:
cross(cross(a, b), cross(a, c))

array([0, 0, 0])

9. Find the equations to the plane containing the heads of the vectors $\vec a$, $\vec b$, and $\vec c$.

10. Show that $(\vec a \times \vec b) \cdot (\vec c \times \vec d) = (\vec b \cdot \vec d)(\vec c \cdot \vec a) - (\vec b \cdot \vec c)(\vec d \cdot \vec a)$.

11. Show that

    $$ \begin{align}(\vec a \times \vec b) \times (\vec c \times \vec d)
        &= [\vec a,\vec b, \vec d]\vec c - [\vec a, \vec b, \vec c]\vec d \\
        &= (\vec c \times \vec d) \times (\vec b \times \vec a) \\
        &= [\vec c, \vec d, \vec a]\vec b - [\vec c, \vec d, \vec b]\vec a
        \end{align}
    $$
    
    Hence show that
    
    $$ [\vec a, \vec b, \vec c]\vec d = [\vec d, \vec b, \vec c]\vec a + [\vec a, \vec d, \vec c]\vec b + [\vec a, \vec b, \vec d]\vec c $$
    
    and deduce the conditions for the unique resolution of the vector $\vec d$ along the three directions $\vec a$, $\vec b$, and $\vec c$.

In [47]:
def vec3(sym: str):
    v = symbols(f'{sym}:3')
    g = globals()
    for i in range(3):
        g[f'{sym}{i}'] = v[i]
    g[f'{sym}'] = v[0]*N.i + v[1]*N.j + v[2]*N.k
    
for x in 'abcd':
    vec3(x)
    
a, b, c, d

In [51]:
a.cross(b).cross(c.cross(d))

In [52]:
simplify(a.cross(b).cross(c.cross(d)))

In [54]:
def triple(a, b, c):
    return a.dot(b.cross(c))

simplify((triple(a, b, d)*c) - (triple(a, b, c)*d) - a.cross(b).cross(c.cross(d)))

In [38]:
simplify(c.cross(d).cross(b.cross(a)) - a.cross(b).cross(c.cross(d)))

In [56]:
simplify(((triple(c, d, a)*b) - (triple(c, d, b)*a)) - a.cross(b).cross(c.cross(d)))

Since we've demonstrated the equivalencies via brute force algebra (hidden in Sympy code), we can take the following given equivalency as axiomatic:

$$ [\vec a,\vec b, \vec d]\vec c - [\vec a, \vec b, \vec c]\vec d = 
   [\vec c, \vec d, \vec a]\vec b - [\vec c, \vec d, \vec b]\vec a
$$

So then we have

$$ \begin{align}
    - [\vec a, \vec b, \vec c]\vec d &= [\vec c, \vec d, \vec a]\vec b - [\vec c, \vec d, \vec b]\vec a - [\vec a,\vec b, \vec d]\vec c \\
    [\vec a, \vec b, \vec c]\vec d &= - [\vec c, \vec d, \vec a]\vec b + [\vec c, \vec d, \vec b]\vec a + [\vec a,\vec b, \vec d]\vec c \\
    &= [\vec c, \vec d, \vec b]\vec a - [\vec c, \vec d, \vec a]\vec b + [\vec a,\vec b, \vec d]\vec c \\
\end{align} $$

Then we can roll the order of the vectors to the left inside the brackets without impacting the magnitude of the triple scalar product. Thus

$$ \begin{align}
    [\vec a, \vec b, \vec c]\vec d &= [\vec c, \vec d, \vec b]\vec a - [\vec c, \vec d, \vec a]\vec b + [\vec a,\vec b, \vec d]\vec c \\
    &= [\vec d, \vec b, \vec c]\vec a + [\vec a, \vec d, \vec c]\vec b + [\vec a,\vec b, \vec d]\vec c
\end{align} $$

An since it looks a little funky, not strictly one of the equalities Danby listed, let's just verify that $-[\vec c, \vec d, \vec a]\vec b = [\vec a, \vec d, \vec c]\vec b$

In [58]:
simplify(-(triple(c, d, a)*b) - (triple(a, d, c)*b))

Interpreting this geometrically, I think this is about change-of-basis, where we're trying to express $\vec d$ in terms of the vectors $\vec a$, $\vec b$, and $\vec c$.

12. Show that

    $$ [\vec a, \vec b, \vec c](\vec f \times \vec g) =
        \left| \begin{matrix}
            \vec a & \vec b & \vec c \\
            \vec f \cdot \vec a & \vec f \cdot \vec b & \vec f \cdot \vec c \\
            \vec g \cdot \vec a & \vec g \cdot \vec b & \vec g \cdot \vec c
        \end {matrix} \right|
    $$
    
    Hence, generalize equation (2.4.2)
    
    $$ \vec b \times \vec c = \left| \begin{matrix}
            \uvec i & \uvec j & \uvec k \\
            b_x & b_y & b_z \\
            c_x & c_y & c_z
        \end{matrix} \right|
    $$

13. Solve for $\vec X$ the equation $\vec X \times \vec a = \vec b$, where $\vec a \cdot \vec b = 0$.

14. Solve the equation $\vec X + \vec a(\vec X \cdot \vec b) = \vec c$. (Try $\cdot \vec b$.)

15. Solve the simultaneous equations $\alpha \vec X + \beta \vec Y = \vec a$ and $\vec X \times \vec Y = \vec b$ where $\vec a \cdot \vec b = 0$.

16. Solve the equation $\vec X \times \vec a + (\vec X \cdot \vec b)\vec c = \vec d$

In [22]:
def vec3(sym):
    v = symbols(f'{sym}:3')
    g = globals()
    for i in range(3):
        g[f'{sym}{i}'] = v[i]
    g[f'{sym}'] = v[0]*N.i + v[1]*N.j + v[2]*N.k

In [23]:
vec3('a')

In [24]:
a